### ISSUE TITLE
np.log missing

### ISSUE THREAD

**Issue by martarek** [dipaco/create_hdri#1]
According to Debevec 1997, when calling `fit_response`, exposure times (variable B) should be `np.log(exposure_time)`. When calling `get_samples(imgs_array, channel, num_samples)`, I think the B variable returned should be np.log(B) and not B to be accurate with the equation. 

Again, according to Debevec 1997, when calling create_radiance_map(imgs, G, w), 

``` python
def map_z_values(exposure_time):
        return np.vectorize(lambda z: G[z] - exposure_time)
```

I think it should also be :

``` python
def map_z_values(exposure_time):
        return np.vectorize(lambda z: G[z] - np.log(exposure_time))
```

**Comment by dipaco** [comment]
Thank you. You are right. I corrected the code according to your suggestions.

**Comment by martarek** [comment]
Thanks!
